import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';


const initialState = {
  timerhit: false,
  elementRef:null,
};


export const timerSlice = createSlice({
  name: 'timermodal',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    time: (state) => {
      console.log("time dis")
      state.timerhit=true;

      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes

    },
    elementRef: (state,action) => {
      console.log("time dis",action)
      state.elementRef=action.payload;

      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes

    },



  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.

});

export const timerStatus = (state) => state.timermodal.timerhit;
export const elementStatus = (state) => state.timermodal.elementRef;


export const { time,elementRef } = timerSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default timerSlice.reducer;
